# Generated by Django 6.0.2 on 2026-03-04 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minilibrary', '0002_genre_book_genres'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField()),
                ('language', models.CharField(max_length=50)),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='minilibrary.book')),
            ],
        ),
    ]
