# Generated by Django 6.0.2 on 2026-03-04 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minilibrary', '0003_bookdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookdetail',
            name='cover_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
