# Generated by Django 6.0.2 on 2026-03-04 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minilibrary', '0006_loan'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='is_returned',
            field=models.BooleanField(default=False),
        ),
    ]
